# Generated by Django 4.1.3 on 2022-11-01 12:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Data',
            fields=[
                ('interests', models.CharField(default='[]', max_length=600)),
                ('experiance', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('username', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
