# Generated by Django 4.1.3 on 2022-11-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='bio',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='user_data',
            name='git',
            field=models.URLField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='instagram',
            field=models.URLField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user_data',
            name='linked_in',
            field=models.URLField(max_length=50, null=True),
        ),
    ]
