# Generated by Django 4.1.2 on 2022-10-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='email',
            field=models.CharField(default='', max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
