# Generated by Django 4.1.3 on 2022-11-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_data_bio_user_data_git_user_data_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='git',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='instagram',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='linked_in',
            field=models.CharField(default='', max_length=20),
        ),
    ]
